name:                cppfilt
version:             0.1.0.0
github:              "0xd34df00d/cppfilt"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2018 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Bindings for C++ demangling routines
category:            System

description:         Please see the README on Github at <https://github.com/0xd34df00d/cppfilt#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring

library:
  source-dirs: src
  when:
  - condition: flag(use-libcpp) || os(darwin)
    then:
        extra-libraries: c++
    else:
        extra-libraries: stdc++

tests:
  cppfilt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cppfilt
    - hspec
benchmarks:
  cppfilt-benchmarks:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cppfilt
    - criterion

flags:
  use-libcpp:
    description: Use libc++ for demangling (if you're building your C++ code with clang) instead of libstdc++
    manual: true
    default: false
